In [1]:
from isoweek import Week

In [2]:
def postWeek(inputYearWeek, gapWeek):
    
    currYear = int(inputYearWeek[0:4])
    currWeek = int(inputYearWeek[4:])
    
    maxWeek = Week.last_week_of_year(currYear).week
    
    if (maxWeek < currWeek + gapWeek):
        iterGap = gapWeek + currWeek - maxWeek
        iterYear = currYear + 1
    
        iterWeek = Week.last_week_of_year(iterYear).week
        
        while (iterGap > 0):
            if (iterWeek < iterGap):
                iterGap = iterGap - iterWeek
                iterYear = iterYear + 1
                iterWeek = Week.last_week_of_year(iterYear).week
            else:
                iterWeek = iterGap
                iterGap = 0
        
        return str(iterYear) + "%02d" %(iterWeek)
    else:
        return str(currYear) + "%02d" %(currWeek + gapWeek)

In [3]:
inputYearWeek = '201912'
gapWeek = 30

In [4]:
currYear = int(inputYearWeek[0:4])
currWeek = int(inputYearWeek[4:])
print(currYear)
print(currWeek)

2019
12

In [5]:
maxWeek = Week.last_week_of_year(currYear).week
maxWeek

52

In [6]:
str(currYear) + "%02d" %(currWeek + gapWeek)

'201942'

In [7]:
if (maxWeek < currWeek + gapWeek):
        iterGap = gapWeek + currWeek - maxWeek
        iterYear = currYear + 1
    
        iterWeek = Week.last_week_of_year(iterYear).week
        print(iterGap)

In [8]:
while (iterGap > 0):
            if (iterWeek < iterGap):
                iterGap = iterGap - iterWeek
                iterYear = iterYear + 1
                iterWeek = Week.last_week_of_year(iterYear).week
            else:
                iterWeek = iterGap
                iterGap = 0

NameError: name 'iterGap' is not defined

In [9]:
import pandas as pd
import numpy as np
import math
from isoweek import Week #preWeek, postWeek

 
# CSV 파일을 읽어 Data Frame 변수에 저장하기
seasonality_dataData = pd.read_csv("./seasonality_data.csv")
# seasonality_dataData = pd.read_csv("./dataset/seasonality_data.csv")
# pro_promotionData = pd.read_csv("./dataset/pro_promotion.csv")
# pro_actual_salesData = pd.read_csv("./dataset/pro_actual_sales.csv")

# 컬럼해더 재정의
# customerData.columns = ['CUSTID','AVGPRICE','EMI','DEVICECOUNT','PRODUCTAGE','CUSTTYPE']

# DataFrame으로 변환 
seasonality_dataData_df= pd.DataFrame(seasonality_dataData)

# 데이터 VIEW
seasonality_dataData.head()

  CONTINENT REGIONID PRODUCTGROUP    PRODUCT  YEARWEEK      QTY
0       N05      A60         PG01  PRODUCT04    201402     71.0
1       N05      A60         PG03  PRODUCT59    201402  22275.0
2       N05      A60         PG02  PRODUCT34    201402   4463.0
3       N05      A60         PG03  PRODUCT47    201402      0.0
4       N05      A60         PG03  PRODUCT56    201402     23.0

In [22]:
seasonality_dataData_df.reset_index()

         index CONTINENT REGIONID PRODUCTGROUP    PRODUCT  YEARWEEK       QTY
0            0       N05      A60         PG01  PRODUCT04    201402      71.0
1            1       N05      A60         PG03  PRODUCT59    201402   22275.0
2            2       N05      A60         PG02  PRODUCT34    201402    4463.0
3            3       N05      A60         PG03  PRODUCT47    201402       0.0
4            4       N05      A60         PG03  PRODUCT56    201402      23.0
5            5       N05      A60         PG03  PRODUCT57    201402      14.0
6            6       N05      A60         PG01  PRODUCT12    201402    1186.0
7            7       N05      A60         PG01  PRODUCT01    201402       7.0
8            8       N05      A60         PG02  PRODUCT33    201402     101.0
9            9       N05      A60         PG03  PRODUCT62    201402     336.0
10          10       N03      A37         PG03  PRODUCT58    201402       0.0
11          11       N03      A37         PG03  PRODUCT59    201402   11492.0
12          12       N03      A37         PG02  PRODUCT34    201402     825.0
13          13       N03      A31         PG03  PRODUCT58    201402       0.0
14          14       N03      A31         PG03  PRODUCT59    201402     560.0
15          15       N03      A31         PG02  PRODUCT34    201402     103.0
16          16       N01      A04         PG03  PRODUCT58    201402       0.0
17          17       N01      A04         PG04  PRODUCT63    201402     740.0
18          18       N01      A04         PG01  PRODUCT15    201402     394.0
19          19       N01      A04         PG01  PRODUCT04    201402    2550.0
20          20       N01      A04         PG01  PRODUCT16    201402       4.0
21          21       N01      A04         PG03  PRODUCT59    201402   36549.0
22          22       N01      A04         PG02  PRODUCT34    201402    4773.0
23          23       N01      A04         PG02  PRODUCT40    201402     146.0
24          24       N01      A04         PG03  PRODUCT47    201402       5.0
25          25       N01      A04         PG03  PRODUCT60    201402       9.0
26          26       N01      A04         PG03  PRODUCT56    201402     109.0
27          27       N01      A04         PG03  PRODUCT57    201402    1195.0
28          28       N01      A04         PG01  PRODUCT12    201402   15028.0
29          29       N01      A04         PG01  PRODUCT01    201402    1319.0
...        ...       ...      ...          ...        ...       ...       ...
124628  124628       N02      A16         PG04  PRODUCT64    201630     188.0
124629  124629       N02      A16         PG03  PRODUCT48    201630      16.0
124630  124630       N02      A16         PG03  PRODUCT49    201630       9.0
124631  124631       N02      A16         PG04  PRODUCT74    201630      18.0
124632  124632       N02      A16         PG02  PRODUCT40    201630     285.0
124633  124633       N02      A16         PG03  PRODUCT47    201630     155.0
124634  124634       N02      A16         PG03  PRODUCT60    201630    2491.0
124635  124635       N02      A16         PG03  PRODUCT56    201630    2026.0
124636  124636       N02      A16         PG01  PRODUCT12    201630   17067.0
124637  124637       N02      A16         PG01  PRODUCT01    201630     168.0
124638  124638       N02      A16         PG02  PRODUCT41    201630       0.0
124639  124639       N02      A16         PG03  PRODUCT51    201630       0.0
124640  124640       N02      A16         PG04  PRODUCT68    201630       0.0
124641  124641       N02      A16         PG02  PRODUCT33    201630    3887.0
124642  124642       N02      A16         PG01  PRODUCT14    201630      95.0
124643  124643       N01      A10         PG01  PRODUCT02    201630   12570.0
124644  124644       N01      A10         PG03  PRODUCT58    201630    4461.0
124645  124645       N01      A10         PG04  PRODUCT63    201630    4308.0
124646  124646       N01      A10         PG01  PRODUCT15    201630       0.0
124647  124647       N01      A10         PG01  PRODUCT04    201630    3012.0
124648  124648       N01      A10         PG01  PRODUCT16    201630     231.0
124649  124649       N01      A10         PG03  PRODUCT59    201630  231024.0
124650  124650       N01      A10         PG02  PRODUCT34    201630   34436.0
124651  124651       N01      A10         PG02  PRODUCT40    201630       0.0
124652  124652       N01      A10         PG03  PRODUCT47    201630       4.0
124653  124653       N01      A10         PG03  PRODUCT60    201630     824.0
124654  124654       N01      A10         PG03  PRODUCT56    201630     275.0
124655  124655       N01      A10         PG03  PRODUCT61    201630       0.0
124656  124656       N01      A10         PG01  PRODUCT12    201630   15021.0
124657  124657       N01      A10         PG01  PRODUCT01    201630     568.0

[124658 rows x 7 columns]

In [10]:
minWeek = seasonality_dataData_df["YEARWEEK"].min()
minWeek

201401

In [11]:
currWeek = seasonality_dataData_df["YEARWEEK"].max()
currWeek

201652

In [12]:
def lagWeek(week1, week2):
    fromWeek = ""
    toWeek = ""

    if (int(week1) < int(week2)):
        fromWeek = week1
        toWeek = week2
    else:
        fromWeek = week2
        toWeek = week1

    # 53주차 제외
    currYear = int(fromWeek[0:4])
    currWeek = int(fromWeek[4:])

    if (52 < currWeek):
        return 0
    
    # 53주차 제외
    currYear = int(toWeek[0:4])
    currWeek = int(toWeek[4:])

    if (52 < currWeek):
        return 0

    calcGapNum = 0
    calcWeek = toWeek

    while (int(fromWeek) != int(calcWeek)):
        calcGapNum = calcGapNum + 1
        calcWeek = preWeek(toWeek, calcGapNum)
    return calcGapNum

In [13]:
# 과거주차 찾기 함수
def preWeek(inputYW, gapW):
    inpYW = str(inputYW) ## 입력 연도주차 문자열 변환
    inpY=inpYW[0:4] ## 입력 연도 추출
    inpW=inpYW[4: ] ## 입력 주차 추출

    inpGap=int(gapW) ## 입력 갭 인트형 확정

    dif = int(inpW) - inpGap ## 입력 갭과 입력 주차의 차

    if(dif>0):
        if(dif<10):
            lastanswer = str(inpY) + "0" + str(dif)
        else:
            lastanswer = str(inpY) + str(dif)
        
    else:
        dif = dif
        preyear = int(inpY)
        while (dif <= 0):
            preyear = preyear - 1
            preweek = Week.last_week_of_year(preyear).week
            dif = dif + preweek
        if(dif<10):
            lastanswer =str(preyear)+"0"+str(dif)
        else:
            lastanswer = str(preyear) + str(dif)

    return lastanswer

In [14]:
gapWeek =lagWeek(str(minWeek),str(currWeek))
gapWeek

156

In [15]:
allWeekArray = []
startWeek = minWeek
endWeek = currWeek
i = 0

In [16]:
def postWeek(inputYearWeek, gapWeek):
    
    currYear = int(inputYearWeek[0:4])
    currWeek = int(inputYearWeek[4:])
    
    maxWeek = Week.last_week_of_year(currYear).week
    
    if (maxWeek < currWeek + gapWeek):
        iterGap = gapWeek + currWeek - maxWeek
        iterYear = currYear + 1
    
        iterWeek = Week.last_week_of_year(iterYear).week
        
        while (iterGap > 0):
            if (iterWeek < iterGap):
                iterGap = iterGap - iterWeek
                iterYear = iterYear + 1
                iterWeek = Week.last_week_of_year(iterYear).week
            else:
                iterWeek = iterGap
                iterGap = 0
        
        return str(iterYear) + "%02d" %(iterWeek)
    else:
        return str(currYear) + "%02d" %(currWeek + gapWeek)

In [17]:
postWeek(str(startWeek),gapWeek)

'201652'

In [18]:
while(i <= gapWeek):
    allWeekArray.append(int(postWeek(str(startWeek), i)))
    i=i+1

In [19]:
allWeekArray

[201401,
 201402,
 201403,
 201404,
 201405,
 201406,
 201407,
 201408,
 201409,
 201410,
 201411,
 201412,
 201413,
 201414,
 201415,
 201416,
 201417,
 201418,
 201419,
 201420,
 201421,
 201422,
 201423,
 201424,
 201425,
 201426,
 201427,
 201428,
 201429,
 201430,
 201431,
 201432,
 201433,
 201434,
 201435,
 201436,
 201437,
 201438,
 201439,
 201440,
 201441,
 201442,
 201443,
 201444,
 201445,
 201446,
 201447,
 201448,
 201449,
 201450,
 201451,
 201452,
 201501,
 201502,
 201503,
 201504,
 201505,
 201506,
 201507,
 201508,
 201509,
 201510,
 201511,
 201512,
 201513,
 201514,
 201515,
 201516,
 201517,
 201518,
 201519,
 201520,
 201521,
 201522,
 201523,
 201524,
 201525,
 201526,
 201527,
 201528,
 201529,
 201530,
 201531,
 201532,
 201533,
 201534,
 201535,
 201536,
 201537,
 201538,
 201539,
 201540,
 201541,
 201542,
 201543,
 201544,
 201545,
 201546,
 201547,
 201548,
 201549,
 201550,
 201551,
 201552,
 201553,
 201601,
 201602,
 201603,
 201604,
 201605,
 201606,
 201607,
 201608,
 201609,
 201610,
 201611,
 201612,
 201613,
 201614,
 201615,
 201616,
 201617,
 201618,
 201619,
 201620,
 201621,
 201622,
 201623,
 201624,
 201625,
 201626,
 201627,
 201628,
 201629,
 201630,
 201631,
 201632,
 201633,
 201634,
 201635,
 201636,
 201637,
 201638,
 201639,
 201640,
 201641,
 201642,
 201643,
 201644,
 201645,
 201646,
 201647,
 201648,
 201649,
 201650,
 201651,
 201652]

In [20]:
allWeekset = set(allWeekArray)
allWeekset

{201401,
 201402,
 201403,
 201404,
 201405,
 201406,
 201407,
 201408,
 201409,
 201410,
 201411,
 201412,
 201413,
 201414,
 201415,
 201416,
 201417,
 201418,
 201419,
 201420,
 201421,
 201422,
 201423,
 201424,
 201425,
 201426,
 201427,
 201428,
 201429,
 201430,
 201431,
 201432,
 201433,
 201434,
 201435,
 201436,
 201437,
 201438,
 201439,
 201440,
 201441,
 201442,
 201443,
 201444,
 201445,
 201446,
 201447,
 201448,
 201449,
 201450,
 201451,
 201452,
 201501,
 201502,
 201503,
 201504,
 201505,
 201506,
 201507,
 201508,
 201509,
 201510,
 201511,
 201512,
 201513,
 201514,
 201515,
 201516,
 201517,
 201518,
 201519,
 201520,
 201521,
 201522,
 201523,
 201524,
 201525,
 201526,
 201527,
 201528,
 201529,
 201530,
 201531,
 201532,
 201533,
 201534,
 201535,
 201536,
 201537,
 201538,
 201539,
 201540,
 201541,
 201542,
 201543,
 201544,
 201545,
 201546,
 201547,
 201548,
 201549,
 201550,
 201551,
 201552,
 201553,
 201601,
 201602,
 201603,
 201604,
 201605,
 201606,
 201607,
 201608,
 201609,
 201610,
 201611,
 201612,
 201613,
 201614,
 201615,
 201616,
 201617,
 201618,
 201619,
 201620,
 201621,
 201622,
 201623,
 201624,
 201625,
 201626,
 201627,
 201628,
 201629,
 201630,
 201631,
 201632,
 201633,
 201634,
 201635,
 201636,
 201637,
 201638,
 201639,
 201640,
 201641,
 201642,
 201643,
 201644,
 201645,
 201646,
 201647,
 201648,
 201649,
 201650,
 201651,
 201652}

In [21]:
groupby_fillWEEK = seasonality_dataData_df.groupby(["CONTINENT","REGIONID", "PRODUCTGROUP", "PRODUCT"])[["YEARWEEK"]]

In [22]:
groupby_fillWEEK.head()

      YEARWEEK
0       201402
1       201402
2       201402
3       201402
4       201402
5       201402
6       201402
7       201402
8       201402
9       201402
10      201402
11      201402
12      201402
13      201402
14      201402
15      201402
16      201402
17      201402
18      201402
19      201402
20      201402
21      201402
22      201402
23      201402
24      201402
25      201402
26      201402
27      201402
28      201402
29      201402
...        ...
4638    201406
4639    201406
4640    201406
4641    201406
4642    201406
4643    201406
4644    201406
4645    201406
4646    201406
4647    201406
4648    201406
4649    201406
4650    201406
4651    201406
4652    201406
4653    201406
4654    201406
4655    201406
4656    201406
4657    201406
4658    201406
4659    201406
4660    201406
4661    201406
4662    201406
4663    201406
4664    201406
4665    201406
4666    201406
4667    201406

[3970 rows x 1 columns]

In [23]:
seasonality_dataData.columns[0]

'CONTINENT'

In [24]:
data = {}
for columnName in seasonality_dataData.columns:#컬럼명들이 리스트로 넘어가
    data[columnName]= []

In [25]:
data[columnName]

[]

In [26]:
data

{'CONTINENT': [],
 'PRODUCT': [],
 'PRODUCTGROUP': [],
 'QTY': [],
 'REGIONID': [],
 'YEARWEEK': []}

In [27]:
group[access].YEARWEEK

NameError: name 'group' is not defined

In [28]:
groupby_fillWEEK[0]

Exception: Column(s) ['YEARWEEK'] already selected

In [54]:
for group in groupby_fillWEEK:#위에서 기본키 연결 yearweek
    access = 1 # 개별 그룹바이 결과 접근하기 위한 파라미터
    eachGroup = group[access].YEARWEEK
    weekArray=[]

In [30]:
group[access].YEARWEEK.min()

201401

In [31]:
type(groupby_fillWEEK)

pandas.core.groupby.DataFrameGroupBy

In [32]:
type(group)

tuple

In [33]:
group[0]

('N05', 'A77', 'PG01', 'PRODUCT12')

In [34]:
group[1]

       CONTINENT REGIONID PRODUCTGROUP    PRODUCT  YEARWEEK      QTY
176          N05      A77         PG01  PRODUCT12    201404   2628.0
269          N05      A77         PG01  PRODUCT12    201401   3821.0
1728         N05      A77         PG01  PRODUCT12    201402   2466.0
2711         N05      A77         PG01  PRODUCT12    201405   1442.0
3096         N05      A77         PG01  PRODUCT12    201403   2401.0
4105         N05      A77         PG01  PRODUCT12    201406   3794.0
6259         N05      A77         PG01  PRODUCT12    201407   2409.0
6653         N05      A77         PG01  PRODUCT12    201409   2587.0
7733         N05      A77         PG01  PRODUCT12    201408   2619.0
8644         N05      A77         PG01  PRODUCT12    201410   2038.0
9892         N05      A77         PG01  PRODUCT12    201412   1678.0
10094        N05      A77         PG01  PRODUCT12    201411   2593.0
10784        N05      A77         PG01  PRODUCT12    201413   2816.0
11245        N05      A77         PG01  PRODUCT12    201414   2837.0
12099        N05      A77         PG01  PRODUCT12    201415   1766.0
12789        N05      A77         PG01  PRODUCT12    201417   1910.0
13408        N05      A77         PG01  PRODUCT12    201416   1026.0
14415        N05      A77         PG01  PRODUCT12    201418    903.0
15429        N05      A77         PG01  PRODUCT12    201420   1460.0
15799        N05      A77         PG01  PRODUCT12    201419    786.0
16937        N05      A77         PG01  PRODUCT12    201422   1825.0
17050        N05      A77         PG01  PRODUCT12    201421   1016.0
17624        N05      A77         PG01  PRODUCT12    201423   1541.0
19436        N05      A77         PG01  PRODUCT12    201424   2214.0
20680        N05      A77         PG01  PRODUCT12    201436   1590.0
20720        N05      A77         PG01  PRODUCT12    201440   1365.0
21230        N05      A77         PG01  PRODUCT12    201450   3537.0
21687        N05      A77         PG01  PRODUCT12    201520   3671.0
21903        N05      A77         PG01  PRODUCT12    201517   4089.0
22037        N05      A77         PG01  PRODUCT12    201432   1687.0
...          ...      ...          ...        ...       ...      ...
101444       N05      A77         PG01  PRODUCT12    201626   4815.0
101638       N05      A77         PG01  PRODUCT12    201632   5863.0
101823       N05      A77         PG01  PRODUCT12    201617   3421.0
102292       N05      A77         PG01  PRODUCT12    201648   4152.0
102329       N05      A77         PG01  PRODUCT12    201650   5846.0
103153       N05      A77         PG01  PRODUCT12    201647   3574.0
103773       N05      A77         PG01  PRODUCT12    201628   3319.0
105534       N05      A77         PG01  PRODUCT12    201612   3576.0
107400       N05      A77         PG01  PRODUCT12    201604   5044.0
108564       N05      A77         PG01  PRODUCT12    201644   4109.0
108820       N05      A77         PG01  PRODUCT12    201636   3742.0
108987       N05      A77         PG01  PRODUCT12    201614   7854.0
109995       N05      A77         PG01  PRODUCT12    201613   4058.0
110020       N05      A77         PG01  PRODUCT12    201620   3496.0
110902       N05      A77         PG01  PRODUCT12    201610   4731.0
111498       N05      A77         PG01  PRODUCT12    201609   4233.0
111700       N05      A77         PG01  PRODUCT12    201637   3002.0
113316       N05      A77         PG01  PRODUCT12    201547   5240.0
113557       N05      A77         PG01  PRODUCT12    201639  14734.0
115842       N05      A77         PG01  PRODUCT12    201618   2780.0
117322       N05      A77         PG01  PRODUCT12    201616   4659.0
117573       N05      A77         PG01  PRODUCT12    201641   4010.0
118386       N05      A77         PG01  PRODUCT12    201638   5583.0
118523       N05      A77         PG01  PRODUCT12    201640   3603.0
119712       N05      A77         PG01  PRODUCT12    201548   4519.0
121416       N05      A77         PG01  PRODUCT12    201642   4292.0
122120       N05      A77         PG01  PRODUCT12    201630   7120.0
122700       N05      A77         PG01  PRODUCT12    201635   3624.0
124466       N05      A77         PG01  PRODUCT12    201634   4019.0
124470       N05      A77         PG01  PRODUCT12    201627   3002.0

[157 rows x 6 columns]

In [44]:
group[1].YEARWEEK

176       201404
269       201401
1728      201402
2711      201405
3096      201403
4105      201406
6259      201407
6653      201409
7733      201408
8644      201410
9892      201412
10094     201411
10784     201413
11245     201414
12099     201415
12789     201417
13408     201416
14415     201418
15429     201420
15799     201419
16937     201422
17050     201421
17624     201423
19436     201424
20680     201436
20720     201440
21230     201450
21687     201520
21903     201517
22037     201432
           ...
101444    201626
101638    201632
101823    201617
102292    201648
102329    201650
103153    201647
103773    201628
105534    201612
107400    201604
108564    201644
108820    201636
108987    201614
109995    201613
110020    201620
110902    201610
111498    201609
111700    201637
113316    201547
113557    201639
115842    201618
117322    201616
117573    201641
118386    201638
118523    201640
119712    201548
121416    201642
122120    201630
122700    201635
124466    201634
124470    201627
Name: YEARWEEK, Length: 157, dtype: int64

In [36]:
type(eachGroup)

pandas.core.series.Series

In [37]:
eachGroup.head()

176     201404
269     201401
1728    201402
2711    201405
3096    201403
Name: YEARWEEK, dtype: int64

In [38]:
data

{'CONTINENT': [],
 'PRODUCT': [],
 'PRODUCTGROUP': [],
 'QTY': [],
 'REGIONID': [],
 'YEARWEEK': []}

In [39]:
data['CONTINENT']

[]

In [42]:
for weekData in eachGroup:
    weekArray.append(weekData)

In [43]:
weekArray

[201404,
 201401,
 201402,
 201405,
 201403,
 201406,
 201407,
 201409,
 201408,
 201410,
 201412,
 201411,
 201413,
 201414,
 201415,
 201417,
 201416,
 201418,
 201420,
 201419,
 201422,
 201421,
 201423,
 201424,
 201436,
 201440,
 201450,
 201520,
 201517,
 201432,
 201426,
 201433,
 201512,
 201428,
 201429,
 201438,
 201509,
 201533,
 201503,
 201511,
 201514,
 201502,
 201504,
 201516,
 201507,
 201535,
 201513,
 201501,
 201518,
 201508,
 201505,
 201510,
 201541,
 201444,
 201441,
 201442,
 201435,
 201430,
 201425,
 201448,
 201515,
 201445,
 201536,
 201506,
 201437,
 201452,
 201439,
 201443,
 201431,
 201434,
 201451,
 201427,
 201538,
 201447,
 201449,
 201446,
 201625,
 201606,
 201542,
 201622,
 201624,
 201545,
 201546,
 201551,
 201540,
 201528,
 201619,
 201550,
 201621,
 201544,
 201602,
 201534,
 201623,
 201543,
 201549,
 201532,
 201607,
 201523,
 201553,
 201603,
 201605,
 201552,
 201537,
 201522,
 201601,
 201531,
 201539,
 201521,
 201527,
 201530,
 201524,
 201526,
 201519,
 201529,
 201525,
 201629,
 201608,
 201652,
 201643,
 201631,
 201649,
 201615,
 201645,
 201646,
 201611,
 201651,
 201633,
 201626,
 201632,
 201617,
 201648,
 201650,
 201647,
 201628,
 201612,
 201604,
 201644,
 201636,
 201614,
 201613,
 201620,
 201610,
 201609,
 201637,
 201547,
 201639,
 201618,
 201616,
 201641,
 201638,
 201640,
 201548,
 201642,
 201630,
 201635,
 201634,
 201627]

In [67]:
weekSet= set(weekArray)
print("weekSet 값: " , weekSet)
newWeekset = allWeekset.difference(weekSet)#차집합
print("newWeekset 값: ", newWeekset)
#      그룹바이한 각각의 그룹에 대한 연주차 정보가 비어있지 않으면 그룹바이의 다음 그룹으로 넘어간다.

weekSet 값:  set()
newWeekset 값:  {201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201410, 201411, 201412, 201413, 201414, 201415, 201416, 201417, 201418, 201419, 201420, 201421, 201422, 201423, 201424, 201425, 201426, 201427, 201428, 201429, 201430, 201431, 201432, 201433, 201434, 201435, 201436, 201437, 201438, 201439, 201440, 201441, 201442, 201443, 201444, 201445, 201446, 201447, 201448, 201449, 201450, 201451, 201452, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512, 201513, 201514, 201515, 201516, 201517, 201518, 201519, 201520, 201521, 201522, 201523, 201524, 201525, 201526, 201527, 201528, 201529, 201530, 201531, 201532, 201533, 201534, 201535, 201536, 201537, 201538, 201539, 201540, 201541, 201542, 201543, 201544, 201545, 201546, 201547, 201548, 201549, 201550, 201551, 201552, 201553, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612, 201613, 201614, 201615, 201616, 201617, 201618, 201619, 201620, 201621, 201622, 201623, 201624, 201625, 201626, 201627, 201628, 201629, 201630, 201631, 201632, 201633, 201634, 201635, 201636, 201637, 201638, 201639, 201640, 201641, 201642, 201643, 201644, 201645, 201646, 201647, 201648, 201649, 201650, 201651, 201652}

In [68]:
if(len(newWeekset)==0):
    continue

CONTINENTcolNum = 0
REGIONIDcolNum = 1
PRODUCTGROUPcolNum = 2
PRODUCTcolNum = 3

for eachGroup in group:        
    if(newWeekset != None):
        print(newWeekset)
        for insertRawData in newWeekset:
            data["CONTINENT"].append(eachGroup[CONTINENTcolNum])#[]빈칸에 append.
            data["REGIONID"].append(eachGroup[REGIONIDcolNum])
            data["PRODUCTGROUP"].append(eachGroup[PRODUCTGROUPcolNum])
            data["PRODUCT"].append(eachGroup[PRODUCTcolNum])
            data["YEARWEEK"].append(insertRawData)
            data["QTY"].append(0)
            cnt=cnt+1
        break

print("추가 행 개수: ", cnt)
print(data)
print(type(data))
print("-------------------")
print("-------------------")
addDf = pd.DataFrame(data=data)
print(addDf)
print("-------------------")
print("-------------------")

SyntaxError: 'continue' not properly in loop (<ipython-input-68-abe583fe9af9>, line 2)